# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/inamdara/ICS45c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/inamdara/ICS45c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inamdara/ICS45c/CMakeFiles /home/inamdara/ICS45c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inamdara/ICS45c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named word_count

# Build rule for target.
word_count: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 word_count
.PHONY : word_count

# fast build rule for target.
word_count/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count.dir/build.make CMakeFiles/word_count.dir/build
.PHONY : word_count/fast

#=============================================================================
# Target rules for targets named coins_simple

# Build rule for target.
coins_simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coins_simple
.PHONY : coins_simple

# fast build rule for target.
coins_simple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_simple.dir/build.make CMakeFiles/coins_simple.dir/build
.PHONY : coins_simple/fast

#=============================================================================
# Target rules for targets named coins_menu

# Build rule for target.
coins_menu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coins_menu
.PHONY : coins_menu

# fast build rule for target.
coins_menu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_menu.dir/build.make CMakeFiles/coins_menu.dir/build
.PHONY : coins_menu/fast

#=============================================================================
# Target rules for targets named coins_transfer

# Build rule for target.
coins_transfer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coins_transfer
.PHONY : coins_transfer

# fast build rule for target.
coins_transfer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_transfer.dir/build.make CMakeFiles/coins_transfer.dir/build
.PHONY : coins_transfer/fast

#=============================================================================
# Target rules for targets named word_count_gtests

# Build rule for target.
word_count_gtests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 word_count_gtests
.PHONY : word_count_gtests

# fast build rule for target.
word_count_gtests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/build
.PHONY : word_count_gtests/fast

#=============================================================================
# Target rules for targets named coins_gtests

# Build rule for target.
coins_gtests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coins_gtests
.PHONY : coins_gtests

# fast build rule for target.
coins_gtests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/build
.PHONY : coins_gtests/fast

#=============================================================================
# Target rules for targets named student_gtests

# Build rule for target.
student_gtests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 student_gtests
.PHONY : student_gtests

# fast build rule for target.
student_gtests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/build
.PHONY : student_gtests/fast

gtest/coins_gtests.o: gtest/coins_gtests.cpp.o
.PHONY : gtest/coins_gtests.o

# target to build an object file
gtest/coins_gtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/gtest/coins_gtests.cpp.o
.PHONY : gtest/coins_gtests.cpp.o

gtest/coins_gtests.i: gtest/coins_gtests.cpp.i
.PHONY : gtest/coins_gtests.i

# target to preprocess a source file
gtest/coins_gtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/gtest/coins_gtests.cpp.i
.PHONY : gtest/coins_gtests.cpp.i

gtest/coins_gtests.s: gtest/coins_gtests.cpp.s
.PHONY : gtest/coins_gtests.s

# target to generate assembly for a file
gtest/coins_gtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/gtest/coins_gtests.cpp.s
.PHONY : gtest/coins_gtests.cpp.s

gtest/gtestmain.o: gtest/gtestmain.cpp.o
.PHONY : gtest/gtestmain.o

# target to build an object file
gtest/gtestmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/gtest/gtestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/gtest/gtestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/gtest/gtestmain.cpp.o
.PHONY : gtest/gtestmain.cpp.o

gtest/gtestmain.i: gtest/gtestmain.cpp.i
.PHONY : gtest/gtestmain.i

# target to preprocess a source file
gtest/gtestmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/gtest/gtestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/gtest/gtestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/gtest/gtestmain.cpp.i
.PHONY : gtest/gtestmain.cpp.i

gtest/gtestmain.s: gtest/gtestmain.cpp.s
.PHONY : gtest/gtestmain.s

# target to generate assembly for a file
gtest/gtestmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/gtest/gtestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/gtest/gtestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/gtest/gtestmain.cpp.s
.PHONY : gtest/gtestmain.cpp.s

gtest/word_count_gtests.o: gtest/word_count_gtests.cpp.o
.PHONY : gtest/word_count_gtests.o

# target to build an object file
gtest/word_count_gtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/gtest/word_count_gtests.cpp.o
.PHONY : gtest/word_count_gtests.cpp.o

gtest/word_count_gtests.i: gtest/word_count_gtests.cpp.i
.PHONY : gtest/word_count_gtests.i

# target to preprocess a source file
gtest/word_count_gtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/gtest/word_count_gtests.cpp.i
.PHONY : gtest/word_count_gtests.cpp.i

gtest/word_count_gtests.s: gtest/word_count_gtests.cpp.s
.PHONY : gtest/word_count_gtests.s

# target to generate assembly for a file
gtest/word_count_gtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/gtest/word_count_gtests.cpp.s
.PHONY : gtest/word_count_gtests.cpp.s

src/coins.o: src/coins.cpp.o
.PHONY : src/coins.o

# target to build an object file
src/coins.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_simple.dir/build.make CMakeFiles/coins_simple.dir/src/coins.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_menu.dir/build.make CMakeFiles/coins_menu.dir/src/coins.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_transfer.dir/build.make CMakeFiles/coins_transfer.dir/src/coins.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/src/coins.cpp.o
.PHONY : src/coins.cpp.o

src/coins.i: src/coins.cpp.i
.PHONY : src/coins.i

# target to preprocess a source file
src/coins.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_simple.dir/build.make CMakeFiles/coins_simple.dir/src/coins.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_menu.dir/build.make CMakeFiles/coins_menu.dir/src/coins.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_transfer.dir/build.make CMakeFiles/coins_transfer.dir/src/coins.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/src/coins.cpp.i
.PHONY : src/coins.cpp.i

src/coins.s: src/coins.cpp.s
.PHONY : src/coins.s

# target to generate assembly for a file
src/coins.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_simple.dir/build.make CMakeFiles/coins_simple.dir/src/coins.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_menu.dir/build.make CMakeFiles/coins_menu.dir/src/coins.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_transfer.dir/build.make CMakeFiles/coins_transfer.dir/src/coins.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_gtests.dir/build.make CMakeFiles/coins_gtests.dir/src/coins.cpp.s
.PHONY : src/coins.cpp.s

src/coins_menu.o: src/coins_menu.cpp.o
.PHONY : src/coins_menu.o

# target to build an object file
src/coins_menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_menu.dir/build.make CMakeFiles/coins_menu.dir/src/coins_menu.cpp.o
.PHONY : src/coins_menu.cpp.o

src/coins_menu.i: src/coins_menu.cpp.i
.PHONY : src/coins_menu.i

# target to preprocess a source file
src/coins_menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_menu.dir/build.make CMakeFiles/coins_menu.dir/src/coins_menu.cpp.i
.PHONY : src/coins_menu.cpp.i

src/coins_menu.s: src/coins_menu.cpp.s
.PHONY : src/coins_menu.s

# target to generate assembly for a file
src/coins_menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_menu.dir/build.make CMakeFiles/coins_menu.dir/src/coins_menu.cpp.s
.PHONY : src/coins_menu.cpp.s

src/coins_simple.o: src/coins_simple.cpp.o
.PHONY : src/coins_simple.o

# target to build an object file
src/coins_simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_simple.dir/build.make CMakeFiles/coins_simple.dir/src/coins_simple.cpp.o
.PHONY : src/coins_simple.cpp.o

src/coins_simple.i: src/coins_simple.cpp.i
.PHONY : src/coins_simple.i

# target to preprocess a source file
src/coins_simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_simple.dir/build.make CMakeFiles/coins_simple.dir/src/coins_simple.cpp.i
.PHONY : src/coins_simple.cpp.i

src/coins_simple.s: src/coins_simple.cpp.s
.PHONY : src/coins_simple.s

# target to generate assembly for a file
src/coins_simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_simple.dir/build.make CMakeFiles/coins_simple.dir/src/coins_simple.cpp.s
.PHONY : src/coins_simple.cpp.s

src/coins_transfer.o: src/coins_transfer.cpp.o
.PHONY : src/coins_transfer.o

# target to build an object file
src/coins_transfer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_transfer.dir/build.make CMakeFiles/coins_transfer.dir/src/coins_transfer.cpp.o
.PHONY : src/coins_transfer.cpp.o

src/coins_transfer.i: src/coins_transfer.cpp.i
.PHONY : src/coins_transfer.i

# target to preprocess a source file
src/coins_transfer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_transfer.dir/build.make CMakeFiles/coins_transfer.dir/src/coins_transfer.cpp.i
.PHONY : src/coins_transfer.cpp.i

src/coins_transfer.s: src/coins_transfer.cpp.s
.PHONY : src/coins_transfer.s

# target to generate assembly for a file
src/coins_transfer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coins_transfer.dir/build.make CMakeFiles/coins_transfer.dir/src/coins_transfer.cpp.s
.PHONY : src/coins_transfer.cpp.s

src/student_gtests.o: src/student_gtests.cpp.o
.PHONY : src/student_gtests.o

# target to build an object file
src/student_gtests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/src/student_gtests.cpp.o
.PHONY : src/student_gtests.cpp.o

src/student_gtests.i: src/student_gtests.cpp.i
.PHONY : src/student_gtests.i

# target to preprocess a source file
src/student_gtests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/src/student_gtests.cpp.i
.PHONY : src/student_gtests.cpp.i

src/student_gtests.s: src/student_gtests.cpp.s
.PHONY : src/student_gtests.s

# target to generate assembly for a file
src/student_gtests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/src/student_gtests.cpp.s
.PHONY : src/student_gtests.cpp.s

src/word_count.o: src/word_count.cpp.o
.PHONY : src/word_count.o

# target to build an object file
src/word_count.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count.dir/build.make CMakeFiles/word_count.dir/src/word_count.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/src/word_count.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/src/word_count.cpp.o
.PHONY : src/word_count.cpp.o

src/word_count.i: src/word_count.cpp.i
.PHONY : src/word_count.i

# target to preprocess a source file
src/word_count.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count.dir/build.make CMakeFiles/word_count.dir/src/word_count.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/src/word_count.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/src/word_count.cpp.i
.PHONY : src/word_count.cpp.i

src/word_count.s: src/word_count.cpp.s
.PHONY : src/word_count.s

# target to generate assembly for a file
src/word_count.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count.dir/build.make CMakeFiles/word_count.dir/src/word_count.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count_gtests.dir/build.make CMakeFiles/word_count_gtests.dir/src/word_count.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/student_gtests.dir/build.make CMakeFiles/student_gtests.dir/src/word_count.cpp.s
.PHONY : src/word_count.cpp.s

src/word_count_main.o: src/word_count_main.cpp.o
.PHONY : src/word_count_main.o

# target to build an object file
src/word_count_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count.dir/build.make CMakeFiles/word_count.dir/src/word_count_main.cpp.o
.PHONY : src/word_count_main.cpp.o

src/word_count_main.i: src/word_count_main.cpp.i
.PHONY : src/word_count_main.i

# target to preprocess a source file
src/word_count_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count.dir/build.make CMakeFiles/word_count.dir/src/word_count_main.cpp.i
.PHONY : src/word_count_main.cpp.i

src/word_count_main.s: src/word_count_main.cpp.s
.PHONY : src/word_count_main.s

# target to generate assembly for a file
src/word_count_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/word_count.dir/build.make CMakeFiles/word_count.dir/src/word_count_main.cpp.s
.PHONY : src/word_count_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... coins_gtests"
	@echo "... coins_menu"
	@echo "... coins_simple"
	@echo "... coins_transfer"
	@echo "... student_gtests"
	@echo "... word_count"
	@echo "... word_count_gtests"
	@echo "... gtest/coins_gtests.o"
	@echo "... gtest/coins_gtests.i"
	@echo "... gtest/coins_gtests.s"
	@echo "... gtest/gtestmain.o"
	@echo "... gtest/gtestmain.i"
	@echo "... gtest/gtestmain.s"
	@echo "... gtest/word_count_gtests.o"
	@echo "... gtest/word_count_gtests.i"
	@echo "... gtest/word_count_gtests.s"
	@echo "... src/coins.o"
	@echo "... src/coins.i"
	@echo "... src/coins.s"
	@echo "... src/coins_menu.o"
	@echo "... src/coins_menu.i"
	@echo "... src/coins_menu.s"
	@echo "... src/coins_simple.o"
	@echo "... src/coins_simple.i"
	@echo "... src/coins_simple.s"
	@echo "... src/coins_transfer.o"
	@echo "... src/coins_transfer.i"
	@echo "... src/coins_transfer.s"
	@echo "... src/student_gtests.o"
	@echo "... src/student_gtests.i"
	@echo "... src/student_gtests.s"
	@echo "... src/word_count.o"
	@echo "... src/word_count.i"
	@echo "... src/word_count.s"
	@echo "... src/word_count_main.o"
	@echo "... src/word_count_main.i"
	@echo "... src/word_count_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

